
= Writing portfolio

I've built this site with xref:https://antora.org/[Antora], xref:https://asciidoc.org/[AsciiDoc], and xref:https://pages.github.com/[GitHub Pages] as a home for my writing samples.
As I continue in my career, I'll add new samples of my work.

If you want to see my past contributions to documentation for open source projects, you can browse my xref:https://github.com/emarsh1995/[GitHub account].

== About me

For just over a decade, I've worked as a Technical Writer for companies of every size.
I've created user- and developer-facing documentation, company style guides, and help articles.
I've also edited work for my professional and academic careers, and occasionally volunteer with manga scanlation (scan + translation) groups to proofread translated scripts.

My passions lie both in language and technology; I entered the workforce in 2014 as a Computer Science co-op, but completed my Undergraduate and Masters degrees studying English language and literature.
I found my academic niche studying medieval English literature (written between the 5th and 15th centuries), and my professional interest in technical documentation for anything and everything.
