site:
  title: Emily Marsh
  url: https://emarsh1995.github.io
  start_page: ROOT:index.adoc
  robots: disallow

content:
  sources:
  - url: .
    branches: HEAD
  - url: https://github.com/emarsh1995/emarsh1995.github.io
    branches: 'master'