site:
  title: Emily Marsh
  url: https://emarsh1995.github.io

content:
  sources:
  - url: https://github.com/emarsh1995/emarsh1995.github.io.git/

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true